### PR TITLE
Louis' branch

### PR DESCRIPTION
**Pull request by Losh19**
Requesting a pull request, I hope it doesn't make any issues

### CODE REVIEW

**Comment by TitanSri** [comment]
I have reviewed this code and there is no conflicts however the UI.java will replace the old one

**Review by FPStruck — APPROVED** [review]
So far it looks good but remember to remove the console print of priv and pub keys when we finalise

**Review by TitanSri — APPROVED** [review]
looks good

**Comment by FPStruck** [comment]
Other than what I wrote, it looks good to go.

**Pull request merged**
